### ISSUE TITLE
Extracting flat clustering while keeping the hierarchical structure but NOT using the plot?

### ISSUE THREAD

**Issue by jessiejamieson** [scikit-learn-contrib/hdbscan#107]
Greetings!

First, thanks for this project. It's pretty fantastic and has helped me tremendously.

Secondly, I'm using a different (but similar) vis for the condensed_tree_ plot that is more effective with large and crazy data sets, but I would like to see what the selected clusters would look like in the vis I was using. However, I don't directly see how to tell which clusters were chosen without using the plot and circling the icicles that were picked, then trying to see in the data where the clustering occured. Ideally, I could do something like ...condensed_tree_.to_networkx() and an attribute for each node in the tree may be 0 if the node was not in the HDBSCAN clustering, and 1 if the node WAS in the HDBSCAN clustering. Perhaps I just don't directly see how to find the flat clustering while keeping the hierarchical data, and if that's the case, I apologize and would appreciate being pointed in the right direction!

Thank you!

**Comment by lmcinnes** [comment]
I think what you want is

    condensed_tree_._select_clusters()

which will return the cluster id numbers of the selected clusters. It's a
"private" method, and not explicitly documented anywhere, so you had no
reason to expect to have found it. On the other hand, it's perfectly
useable.

On another note -- if you have an alternative plot I would love to have it
contributed as an alternative plot open! Please consider adding it as an
extra method in hdbscan/plots.py and submitting a pull request!

**Comment by jessiejamieson** [comment]
Ahh! This function is perfect. Thank you!! 

Also, concerning the vis, I would love to give you more info; do you have an email I can contact you at? 

Cheers!
