### ISSUE TITLE
approximate_predict() fails on several dasets

### ISSUE THREAD

**Issue by remidomingues** [scikit-learn-contrib/hdbscan#109]
Hello,

I'm using the `approximate_predict` function on a fitted HDSBSCAN model with Python 3.4 and version 0.8.10 of the package. Everything runs well most of the time, though for quite a few dataset the prediction cannot be computed and raises an error (see the stacktrace below).

I've looked a bit into the code, and it seems `cluster_tree['parent']` is empty at the prediction step which causes the error. I've also checked the fitted model, and the training data has been correctly distributed among several clusters. Note that this issue is tightly linked to the value assigned to `min_cluster_size` and that the error disappears most of the time when reducing the parameter value (though it appears with `min_cluster_size~=15` for some datasets of a few hundred samples).

This issue can be reproduced using `min_cluster_size=int(len(X) * 0.05)` and the other default parameter values for the following datasets (I'm using a sample of 80% of data that is scaled by `sklearn.preprocessing.scale`): [yeast](https://archive.ics.uci.edu/ml/machine-learning-databases/yeast/yeast.data), [magic gamma](https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data), [wine quality](https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv) and [german](https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data)

Stacktrace below:
```
  File "/usr/local/lib/python3.4/dist-packages/hdbscan/prediction.py", line 398, in 
    min_samples
  File "/usr/local/lib/python3.4/dist-packages/hdbscan/prediction.py", line 293, in _find_cluster_and_probability
    tree_root = cluster_tree['parent'].min()
  File "/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by lmcinnes** [comment]
Definitely a bug. Thanks for the detailed report -- it will make it much
easier to track down exactly what is going wrong. I'll see if I can get
some time to look into this shortly.

**Comment by remidomingues** [comment]
Many thanks for your answer. We are currently writing an experimental paper reviewing outlier detection algorithms and would love to reference this work in our study. We'll wait for your update.

**Comment by lmcinnes** [comment]
I finally got some time to start digging into this -- sorry for the delay. It looks like, on first inspection, a case of all the points being assigned as noise, and hence there are no clusters. Now the predict function shouldn't error in the way it does, but you imply the data is actually classified into several clusters -- and that doesn't appear to be the case for the yeast data set with `min_cluster_size=int(len(X) * 0.05)` that I've tried so far. Can you cite some exact settings that give a number of distinct clusters but still fails on `approximate_predict`? In the meantime I'll get to work having `approximate_predict` behave better in the case of everything classified as noise.

**Comment by remidomingues** [comment]
Thanks a lot! The fix resolved the issue on my side. I guess I mixed up two runs of the algorithm and thought some points were still labelled.
