### ISSUE TITLE
from sklearn.utils import check_array

### ISSUE THREAD

**Issue by tessaberry** [scikit-learn-contrib/hdbscan#124]
lastest versions of sklearn.utils seems to have moved to check_arrays

I changed this in the following locations:

obust_single_linkage_.py
hdbscan_.py

**Comment by tessaberry** [comment]
Sorry, this was my issue, was using anaconda, but for some reason it was importing from my system scikit which was old.  (check_arrays is deprecated)

**Comment by lmcinnes** [comment]
I've done this myself and spent quite some time confused as to why things were suddenly no longer working. If you want to consider adding a Q and A to the FAQ in the documentation for this sort of issue it would be appreciated.
