### ISSUE TITLE
Pickled hdbscan object is very large

### ISSUE THREAD

**Issue by eivindlm** [scikit-learn-contrib/hdbscan#134]
After calling cluster_obj = hdbscan.HDBSCAN(...).fit(data), I am pickling cluster_obj for later prediction use. The resulting pickle file is quite large, and I suspect the reason is the member "_raw_data" of class HDBSCAN. My data is typically 150,000 rows and 15 columns.

Can HDBSCAN perform prediction without access to the raw data, such that it would be safe to in some way remove the raw data from the pickle file?

**Comment by lmcinnes** [comment]
Unfortunately if you want to do prediction after the fact you will need access to the data. The condensed tree is also a very large object which scales linearly with data size. Again, unfortunately, for prediction that can't be helped. It is probably possible to slim down the pickle file somewhat, but I don't believe you could manage a significant cut down and still be able to run the prediction routines. Sorry.

**Comment by eivindlm** [comment]
Thank you for the quick reply!
