### ISSUE TITLE
Problem importing HDBSCAN in Jupyter and Spyder

### ISSUE THREAD

**Issue by econkc** [scikit-learn-contrib/hdbscan#145]
Hi,

I try to import hdbscan in both Jupyter 5.0 and Spyder 3.2 on macOSSierra 10.12.6 but I have got this error message.

```
/Library/Python/2.7/site-packages/hdbscan/__init__.py in <module>()
----> 1 from .hdbscan_ import HDBSCAN, hdbscan
      2 from .robust_single_linkage_ import RobustSingleLinkage, robust_single_linkage
      3 from .validity import validity_index
      4 from .prediction import approximate_predict, membership_vector, all_points_membership_vectors
      5 

/Library/Python/2.7/site-packages/hdbscan/hdbscan_.py in <module>()
     19 from scipy.sparse import csgraph
     20 
---> 21 from ._hdbscan_linkage import (single_linkage,
     22                                mst_linkage_core,
     23                                mst_linkage_core_vector,

ImportError: dlopen(/Library/Python/2.7/site-packages/hdbscan/_hdbscan_linkage.so, 2): Symbol not found: _PyInt_Type
  Referenced from: /Library/Python/2.7/site-packages/hdbscan/_hdbscan_linkage.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/hdbscan/_hdbscan_linkage.so
```

It works fine on Spyder 2.7 on my another mac (same OS)

**Comment by lmcinnes** [comment]
That is very odd, and I admit to being rather baffled. What was your install method? I highly recommend using the conda packages if at all possible as that seems the best way to avoid these strange compiler related issues.

**Comment by econkc** [comment]
I used pip install

**Comment by lmcinnes** [comment]
I'm glad that resolved the issue, although I remain disappointed that it didn't work under pip. That seems to be very system and compiler dependent and very hard to reproduce unfortunately. The main thing is it is now working for you.
