### ISSUE TITLE
Cluster color codes not matching for selected clusters in condensed_tree_ and clusterer.labels_

### ISSUE THREAD

**Issue by Sieboldianus** [scikit-learn-contrib/hdbscan#150]
For some reason, the colors of selected clusters in condensed_tree_ don't seem to match the colors assigned to clusterer.labels_:
![compcolor1](https://user-images.githubusercontent.com/13646666/33879091-a1c90fb2-df2d-11e7-963e-2f9697ae7eea.png)
![comcolor2](https://user-images.githubusercontent.com/13646666/33879097-a367e1f4-df2d-11e7-8852-ecf70f04d7cf.png)

Orange in Fig. 2 is assigned to a relatively small cluster (below 50 points), but in Fig. 1, orange is assigned to the largest cluster of about 128 points (of total 277 points in my test dataset). I have the feeling red in Fig. 2 refers to the orange cluster in Fig. 1.

This is the output of all clusters from the tree:

```python
pdtree = clusterer.condensed_tree_.to_pandas()
print(pdtree[pdtree.child_size > 1])
```

```
     parent  child    lambda_val  child_size
14      277    278  14263.422977          20
15      277    279  14263.422977         243
57      279    280  22791.396195         130
58      279    281  22791.396195          92
70      281    282  24987.788939          12
71      281    283  24987.788939          75
77      283    284  27216.038608          28
78      283    285  27216.038608          46
163     280    286  53545.282797          12
164     280    287  53545.282797          87
229     287    288  80239.500772          36
230     287    289  80239.500772          22
```

And this is my code for assigning colors to both the condensed_tree_ and clusterer.labels_:
```python
clusterer = hdbscan.HDBSCAN(min_cluster_size=10)
clusterer.fit(test_data)
palette = sns.color_palette()
cluster_colors = [sns.desaturate(palette[col], sat) 
                  if col >= 0 else (0.5, 0.5, 0.5) for col, sat in 
                  zip(clusterer.labels_, clusterer.probabilities_)]
plt.scatter(test_data.T[0], test_data.T[1], c=cluster_colors, **plot_kwds)
clusterer.condensed_tree_.plot(select_clusters=True, selection_palette=sns.color_palette())
```

I am referring to the description [here](http://hdbscan.readthedocs.io/en/latest/advanced_hdbscan.html)

**Comment by lmcinnes** [comment]
Definitely a bug. I think there are some mismatches somewhere in how clusters get selected in various different code paths. I'll have to look into it, but unfortunately don't have too much time right now.

**Comment by m-dz** [comment]
I think I can additional example here, but this time `condensed_tree_.plot()` ignores the `allow_single_cluster=False` argument and does "its own" clustering:

```
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from hdbscan import HDBSCAN


palette = sns.color_palette("tab10", 4)


# Generate data
test_data = np.array([[0.0, 0.0], [0.2, 0.0], [1.0, 1.0], [0.8, 1.0], [1.0, 0.8], [0.8, 0.8], [0.0, 1.0], [0.0, 0.8], [0.2, 1.0], [0.2, 0.8]])

# (Unweighted) HDBSCAN
np.random.seed(1)
hdb_unweighted_2 = HDBSCAN(min_cluster_size=3, gen_min_span_tree=True, allow_single_cluster=True).fit(test_data)
print(hdb_unweighted_2.labels_)
cluster_colours = [palette[col] if col >= 0 else (0.0, 0.0, 0.0) for col in hdb_unweighted_2.labels_]
fig = plt.figure()
plt.scatter(test_data.T[0], test_data.T[1], s=80, c=cluster_colours)
fig.suptitle('HDBSCAN 2'); plt.show()

fig = plt.figure()
cd = hdb_unweighted_2.condensed_tree_.plot(select_clusters=True, selection_palette=palette, log_size=True)
fig.suptitle('HDBSCAN 2 condensed tree plot'); plt.show()
```

![image](https://user-images.githubusercontent.com/15376817/33896690-66b442ec-df5b-11e7-9760-4c911c068a1f.png)

![image](https://user-images.githubusercontent.com/15376817/33896698-6af4e0be-df5b-11e7-8a9d-ffc92d7d8536.png)

When `allow_single_cluster=True` colours match:

![image](https://user-images.githubusercontent.com/15376817/33896745-83ace52a-df5b-11e7-98b5-6be5fc196ef5.png)

**Comment by lmcinnes** [comment]
Here is as good as anywhere. I can't promise I will manage to get to this this week, but I greatly appreciate you taking the time to report the error in this much detail.

**Comment by Sieboldianus** [comment]
Great! This is really important to me because I actually find the tree-view absolutely helpful for understanding cluster characteristics in combination with the labels_- view. Many thanks in advance! 

Just out of curiosity:  is there any other way to identify clusters between condensed_tree_ and clusterer.labels_? It looks like this is just a graphic output/index issue, not a deep cluster-identity problem.

**Comment by lmcinnes** [comment]
You just need to ensure that the cluster selection process identifies the clusters in the same order, which is really ensuring the cython code and the simple code sync up -- you are welcome to look at it yourself if you have time. I strongly suspect there is something fairly simple that got missed in some transitions (it used to work).

**Comment by lmcinnes** [comment]
The current master should now have fixed this -- let me know if this is working better for you.

**Comment by m-dz** [comment]
@lmcinnes , as the other one, will test tomorrow. Thanks!

**Comment by Sieboldianus** [comment]
It works:

![download](https://user-images.githubusercontent.com/13646666/33930345-d93d7cac-dfec-11e7-9e80-744acab1c439.png)
![download 1](https://user-images.githubusercontent.com/13646666/33930347-db2be2e2-dfec-11e7-836e-07e10a181ebd.png)

Fantastic! Many thanks lmcinnes!

**Comment by lmcinnes** [comment]
Glad that it was an easy fix this time so I could get it done. Thanks for all the detailed reporting, and testing!

**Comment by m-dz** [comment]
Can confirm, it encircles the yellow root in my example with `allow_single_cluster=True`.
