### ISSUE TITLE
Change clustering based on minimum spanning tree

### ISSUE THREAD

**Issue by aleereza** [scikit-learn-contrib/hdbscan#166]
Hi
Is there a way to change clustering result by changing minimum spanning tree data? for example I need to change distance value of an edge in minimum spanning tree and recalculate the clustering based on that, or I need to use completely different tree and do the clustering based on that.

**Comment by lmcinnes** [comment]
It is certainly *possible* to alter the minimum spanning tree and recompute a clustering from there. That isn't trivial however as you would have to essentially call the requisite internal routines yourself. Given a MST ``min_spanning_tree`` you would need to do something like:

    # Sort edges of the min_spanning_tree by weight
    min_spanning_tree = min_spanning_tree[np.argsort(min_spanning_tree.T[2]), :]

    # Convert edge list into standard hierarchical clustering format
    single_linkage_tree = label(min_spanning_tree)
    
    # Convert the single linkage tree to labels
    results = _tree_to_labels(X,
                                        single_linkage_tree,
                                        min_cluster_size)

where obviously you'll need to fill in an appropriate value to the ``min_cluster_size``.

**Comment by aleereza** [comment]
Thank you!
