### ISSUE TITLE
Suspicious clustering result

### ISSUE THREAD

**Issue by econkc** [scikit-learn-contrib/hdbscan#171]
Hi,

The clusters I have got from the algorithm looks kind of weird. Every cluster has a persistence of 1.0 and when I try to plot condense tree, it throw an error (matplotlib error): 

> OverflowError: cannot convert float infinity to integer

I know it is hard to answer but can you guess what could be the problem? 

Thanks,

**Comment by lmcinnes** [comment]
Something very edge-case-like is happening here. an you share the data at all?

**Comment by econkc** [comment]
The file is attached along and here is my code.
Warning: The file is pretty big and take about 4 hours to run

[data.csv.zip](https://github.com/scikit-learn-contrib/hdbscan/files/1671528/data.csv.zip)

```
import pandas as pd
import hdbscan
import matplotlib.pyplot as plt
from joblib import Memory
import seaborn as sns

df = pd.read_csv('data.csv', sep='\t')

hdbscan = hdbscan.HDBSCAN(min_cluster_size=50000, min_samples=1, memory='temp_file', prediction_data=True)

cluster = hdbscan.fit(df)

print ("Number of clusters: ", cluster.labels_.max()+1)

for i in cluster.cluster_persistence_:
    print (i)

# Plot condensed tree
cluster.condensed_tree_.plot(label_clusters=True, select_clusters=True, selection_palette=sns.color_palette('deep', 8))
```

**Comment by lmcinnes** [comment]
Looking at your code there I would suggest your issue is too large a ``min_cluster_size`` with the result that the condensed tree has no branches at all (hence plotting difficulties). I would also suggest using a min_samples greater than 2 in general. It is probably better to play with alpha if you want more points clustered.

**Comment by econkc** [comment]
After reading through the issues, I think one reason could be the duplications in the data. I am not sure what is the best way that we can deal with this issue at the moment. Any suggestions? Can I just de-dups and fit the model (I know it is not the right solution since we will change the reachability calculation but we should at least get the core clusters right, can we?)

**Comment by lmcinnes** [comment]
Add a very small epsilon noise to the data to jiggle things free of each other.

**Comment by econkc** [comment]
Thank you
