### ISSUE TITLE
Is there a way to save the model for future prediction?

### ISSUE THREAD

**Issue by econkc** [scikit-learn-contrib/hdbscan#172]
Hi,

I wonder if there is a way to save the final model for future prediction? I understand that we can save a joblib object for tuning purpose that might be able to speed up the calculation but is there a way that we can just import the model back into python and use it to predict new data points without refitting the model. I am not sure if the "generate_prediction_data()" function is for this purpose and I cannot find a clear explanation of this function anywhere in the documentation.

Thanks,

**Comment by lmcinnes** [comment]
There is an ``approximate_predict`` function that can take a given model and made predictions for new data points. The ``generate_prediction_data`` needs to be run on the model before ``approximate_predict`` can work. You should be able to pickle a model and restore it later for predictions.

Now the caveat is that ``approximate_predict`` is just that -- it is an approximation based on the clusters already assigned. It will not necessarily give the same answer you would get if you added the new data points and re-clustered from scratch. Hopefully it fills your needs however.

**Comment by econkc** [comment]
I totally understand that predicting the cluster for new data is based on assumption that the cluster remains the same and so the approximate_predict function is exactly what I need.

So, to be clear, are the following steps correct?

fit the model (prediction_date = True) >> generate_prediction_data >> pickle the model >> make prediction later

I guess my question is which object should I pickle? 

Thanks, 

PS. I am very thankful for your contribution and always answer all the questions very quickly. Now many people in my Data Scientist team are aware of this model and they are all love it.

**Comment by lmcinnes** [comment]
The following code would work:

    model = hdbscan.HDBSCAN(prediction_data=True).fit(data)
    labels, membership_strengths = hdbscan.approximate_predict(model, new_data)

If you wanted to save the model to disk and then later with another script load it back up you would pickle to model to disk, then in the other script load the pickled model.

**Comment by econkc** [comment]
Thank you

**Comment by omarhossam214** [comment]
yes you can use joblib 


```
clusterer = hdbscan.HDBSCAN(min_cluster_size=50, prediction_data=True).fit(data) 
filename = 'model.joblib'
joblib.dump(clusterer, filename)
```
