### ISSUE TITLE
Cluster similarity

### ISSUE THREAD

**Issue by rtmatx** [scikit-learn-contrib/hdbscan#178]
I used hdscan clustering on large time series data. The dataset has a million rows and 20 dimensions  after performing dimensionality reduction. I get the results in reasonable amount of time.

I can plot clusters vs time to see how the clusters are moving or emerging from one time state to another. When I look at some of the important features of a cluster using a statistical test, I find something interesting. Let's say there is a cluster c1 in time interval t1 with top feature set as f1 (ex: 5 features and all of them are high in this cluster). A new cluster c2 appears in the time interval t2 at a later stage but with same feature set as f1. And the top features in c2 are also high in value (similar characteristic to f1). 

Is there any way to find the similarity of these two clusters with hdbscan or with any of the function outputs from hdbscan. Since the dataset is big, I am afraid that can't use any distance matrix based analysis to find similarity unless I under-sample heavily. 

Thanks

**Comment by lmcinnes** [comment]
I think that may depend. If you are clustering everything at once then you can look at the condensed tree (either plotting, or exporting to networkx or pandas for analysis). If you are clustering different blocks of time series independently then I'm not sure if there are any tricks you can play. I don't think I quite understand your dataset or what you you are doing with it well enough unfortunately. Still, hopefully there are some avenues to look into ...

**Comment by rtmatx** [comment]
Thanks for your reply. 

I am clustering everything at once. The dataset that I am working on is multi-dimensional time series for an IOT machine which has failures during its course for some time period. Failures can either be due to sudden change in some value(s) or a gradual change in some set of features that caused failure after some time. The reason to use clustering approach is to check if there are any new clusters that are formed before these failures that have caused the failure in the IOT device or if a instant change with anomaly behavior that has caused the failure. 

In condensed trees generated by hdscan, let's say there are nodes 'a' and 'b' which have clusters a1, a2 and b1,b2 respectively. Is it safe to say that clusters a1 and a2 can be more similar than clusters a1, b1 since (a1, a2) are from the same parent branch (node). Is this the way to interpret some sort of similarity from the tree ? Please correct me if I am wrong in this interpretation.

Can the condensed tree be directly imported in to the networkx without any modification ?

**Comment by lmcinnes** [comment]
Yes, your interpretation is correct, clusters with common parents are more similar that clusters have distinct parents. The further you have to go up the tree to find a common ancestor the more different you can consider clusters.

To work with the tree in, say, networkx , you can use the ``to_networkx`` method, which will return a networkx graph representing the tree. Note that the graph includes all the individual noise points falling out of clusters (they will have ids less than the number of samples in your dataset). It can take a little bit of work to get acquainted with the tree structure, but it can be quite a powerful tool for finer grained analysis such as you wish to do here.

**Comment by rtmatx** [comment]
I will find my way on using tree structure with networkx or using pandas analysis. I will post a tutorial when I am successful. 

I have an idea of using hdbscan to find cluster similarity without using condensed tree. I was going through 'Density-Based Clustering Validation' again and again to find some way to use validation metric (since it is already implemented) to find the similarity b/w clusters. 

The approach I am thinking is as follows:

1) Let's say there are `n` number of clusters in the dataset but the current interest is to find out the similarity between `a` and `b` clusters.
2) First check the validation score, DBCV, of the clusters that have been formed (Main cluster system with `n` clusters). If it is high, then proceed to next steps. Reason for this condition is explained in point 4. 
2) Discard the data that doesn't fall in to these clusters and find the validation score for the data with either cluster label `a` or `b` (noise is ignored)
3) If the validation score for this subset with only `a` and `b` clusters, which is based on  Density Separation of a Pair of Clusters (DSPC) and Density Sparseness of a Cluster (DSC), is high, it implies that  a cluster (`a`\`b`) has better density compactness than density separation between `a` and `b`. So there is good chance that these clusters are indeed different. 
4) But, if the validation score is low, it implies that density inside a cluster is lower than the density that separates it from other clusters. This gives an indication that either clusters are similar to each other (because of less distinction b/w them) or both the clusters (`a` and `b`) are bad ( minimal chance as there is a constraint in point 2 for this purpose) 
5) A heatmap plot similar to seaborn correlation plot that can show high and low values of similarity between clusters.

Can you share your comments on this alternative approach that I am seeking and any bottlenecks that might arise during implementation because of the dataset size. 

PS: For my optimal settings (sort of) of hdbscan, I have around 20 clusters for the entire data.

**Comment by rtmatx** [comment]
I tried to implement the approach that I mentioned above and it yielded reasonable results.

**Comment by rtmatx** [comment]
I implemented the approach that I mentioned above and it yielded reasonable results. 

One modification I did from the above approach is to sub-sample the observations for a cluster for which the number of observations are very high. 

As a result, validation score for cluster system (a,b) (without any anomalies), with either cluster a or cluster b or both cluster(s) having higher observations, is very low. This is because, Density Sparseness(DSC) of a sub-sampled cluster is lower than the complete cluster. This can be negated by including all the observations in the cluster at the cost of speed and repeated calculations of  DSC and DSPC. 

Is there any way to store Density Sparseness of a Cluster (DSC) and Density Separation of a Pair of Clusters (DSPC), once it is calculated,  so that it can be accessed quickly for calculations using these values ? 

Also, can you share your comments on the above approach

**Comment by lmcinnes** [comment]
It sounds like a reasonable approach. Personally I am a little wary of the DBCV scores since they involve operations on a minimum spanning tree within a cluster which is not actually unique -- depending on how you construct the MST you can get quite different scores. With that said, it is the best option that I know of without having to go to bleeding edge unpublished research so...

You can certainly compute the DSC of each cluster once and add it as a node attribute to the networkx graph (for example). Computing DSC and DSPC shouldn't be that expensive unless you have a very large dataset, presuming you are pulling the right functions from ``validity.py``. Other than that I'm not sure what more can be done to speed things up.

**Comment by rtmatx** [comment]
Thanks for the comment. The approach to calculate similarity uses only the lowest distance and the not the `k` lowest distances to find compactness in the cluster which makes it less robust. I will check the code more carefully to find a way to compute DSC and DSPC.
