### ISSUE TITLE
Errors while exporting condensed tree to networkx

### ISSUE THREAD

**Issue by rtmatx** [scikit-learn-contrib/hdbscan#179]
I am trying to export my clusterer object to networkx and I received the following errors

`clusterer.condensed_tree_.to_networkx()`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda/envs/env_name/lib/python3.6/site-packages/networkx/classes/function.py in set_node_attributes(G, values, name)
    646         try:  # `values` is a dict
--> 647             for n, v in values.items():
    648                 try:

AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-62-0417c92212b3> in <module>()
----> 1 g = clusterer.condensed_tree_.to_networkx()

~/anaconda/envs/env_name/lib/python3.6/site-packages/hdbscan/plots.py in to_networkx(self)
    450             result.add_edge(row['parent'], row['child'], weight=row['lambda_val'])
    451 
--> 452         set_node_attributes(result, 'size', dict(self._raw_tree[['child', 'child_size']]))
    453 
    454         return result

~/anaconda/envs/env_name/lib/python3.6/site-packages/networkx/classes/function.py in set_node_attributes(G, values, name)
    652         except AttributeError:  # `values` is a constant
    653             for n in G:
--> 654                 G.nodes[n][name] = values
    655     else:  # `values` must be dict of dict
    656         for n, d in values.items():

TypeError: unhashable type: 'dict'
```

I am not sure what is happening with exceptions in networkx caused by hdbscan

**Comment by lmcinnes** [comment]
It looks like the API in networkx may have changed. I'll see if I can fix that for you.

**Comment by lmcinnes** [comment]
In fact this appears to be fixed in master. What version of hdbscan are you currently using? If all else fails please pull master from github and install that ...

**Comment by rtmatx** [comment]
Thanks. I have updated the package to 0.8.12 and it resolved the issue

**Comment by benoitparis** [comment]
Looks like this bug has reappeared in 0.8.19:

    graph = clusterer.condensed_tree_.to_networkx()

Yields:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-11-a02621b438fc> in <module>()
    ----> 1 graph = clusterer.condensed_tree_.to_networkx()
    
    C:\PROGRAM FILES\ANACONDA3\lib\site-packages\hdbscan\plots.py in to_networkx(self)
        474             result.add_edge(row['parent'], row['child'], weight=row['lambda_val'])
        475 
    --> 476         set_node_attributes(result, dict(self._raw_tree[['child', 'child_size']]), 'size')
        477 
        478         return result
    
    C:\PROGRAM FILES\ANACONDA3\lib\site-packages\networkx\classes\function.py in set_node_attributes(G, name, values)
        331 
        332     for node, value in values.items():
    --> 333         G.node[node][name] = value
        334 
        335 
    
    TypeError: unhashable type: 'dict'

Using hdbscan-0.8.19 on windows 10, install through pip.

**Comment by lmcinnes** [comment]
Hmm, I'll have to look at this again. I don't have a lot of time at the moment so it may need to wait a little. Sorry.
