### ISSUE TITLE
Local vs global outlier

### ISSUE THREAD

**Issue by rtmatx** [scikit-learn-contrib/hdbscan#184]
Hi,

I read through the docs and understood that an outlier from hdbscan can either be a local or a global outlier. 

Local outliers are those which are distant (or equidistant) from few cluster centers but not so much when compared to global outliers which are distant from all of the clusters center generated by hdbscan. Is there any approach to identify them distinctively using the membership vector available for outliers or any methods available in hdbscan. 

One approach is to use a threshold on the membership vector. But identifying the threshold to classify an outlier into local or global can be tricky. Second approach is to use the `lambda` at which the outlier is separated from a cluster. If it is separated in the first few levels (at the top of the condensed tree), then it has high chance of being global clusters. Is it easy to find the distance/`lambda` at which it is separated from the cluster ?

I am asking this question as there is a fundamental difference in these outliers positions/properties even though they are classified with a single label -1. So the outlier analysis, if done on all the available outliers, can have different interpretations than when doing the analysis distinctly on both local/global outliers

Thanks

**Comment by lmcinnes** [comment]
I'm not really sure how to answer this question unfortunately. I think the best plan is to read more of the general outlier detection literature -- algorithms like LOF, LoOP, and LOCI are very much akin to GLOSH which is implemented in hdbscan. The original papers on those (or even the wikipedia pages) will give a better description of what all the finer points (local, global, etc.) of outlier detection approaches, and most will apply equally well to GLOSH.

**Comment by rtmatx** [comment]
Thank you Mr. Leland for pointing me in the right direction. I will read more of the outlier detection literature.
