### ISSUE TITLE
allow inf or nan in precomputed distances

### ISSUE THREAD

**Issue by LGro** [scikit-learn-contrib/hdbscan#187]
Hi @lmcinnes, do you see a reason that speaks against allowing nan or inf in the precomputed distance matrix to indicate missing information about pairwise distances. Looking at the `mst_linkage_core` source I'm actually wondering whether that might work straight away without much adaptation.

**Comment by lmcinnes** [comment]
I believe that part should work fine. I think the larger problem will occur in various other parts of the code. In particular the computation of the condensed tree involves computing `lambda` which is `1/distance` which could cause some issues with inf or nan. I don't believe any of that is insurmountable -- but it would require working through all the potential code paths are either verifying correctness or adding suitable guards and alternatives.

It is definitely a worthwhile suggestions, and if I can find the time I will try to work through and see if I can implement it. Thanks for the suggestion!

**Comment by LGro** [comment]
Thanks for pointing out other spots where it's more difficult.  
I might even tackle it myself and provide a pull request. I'll keep you posted!

**Comment by lmcinnes** [comment]
Thanks! A PR would definitely be appreciated if you manage one.
