### ISSUE TITLE
How to prevent "AttributeError: No minimum spanning tree was generated."

### ISSUE THREAD

**Issue by aleereza** [scikit-learn-contrib/hdbscan#188]
Hi
how can I find out minimum spanning tree will not be generated for the data. I have set gen_min_span_tree=True, but sometimes when I want to cluster large number of features I get this error:
```
AttributeError: No minimum spanning tree was generated.This may be due to optimized algorithm variations that skip explicit generation of the spanning tree.
```
Can I change something to have minimum spanning tree anyway?

**Comment by lmcinnes** [comment]
The code is opting for a certain algorithm given the dataset. You can force it to choose a different algorithm using ``algorithm='boruvka_kdtree'`` and that should result in the min spanning tree beign generated. Note that this may make things run slower (or faster possibly?). This obviously isn't documented well, so I should art least fix that at some point.

**Comment by aleereza** [comment]
Thank you.

**Comment by geajack** [comment]
> The code is opting for a certain algorithm given the dataset. You can force it to choose a different algorithm using `algorithm='boruvka_kdtree'` and that should result in the min spanning tree beign generated. Note that this may make things run slower (or faster possibly?). This obviously isn't documented well, so I should art least fix that at some point.

This doesn't seem to work anymore, at least not with my data. Could it be because my data is 1d?
