### ISSUE TITLE
Difference between normal and cosine distance variants unclear

### ISSUE THREAD

**Issue by ixxie** [scikit-learn-contrib/hdbscan#190]
HDBSCAN has two variant packages in Pypi, both with identical descriptions: the [normal variant](https://pypi.python.org/pypi/hdbscan/0.8.12), and the [cosine distance variant](https://pypi.python.org/pypi/hdbscan-with-cosine-distance/0.8.1). Both point to https://github.com/lmcinnes/hdbscan but I understand the main repo is here now, so these might need to be updated as well. Since there is no branch called *cosine distance* or something like that, I cannot see any documentation of the difference between these packages. This is being requested by reviewers downstream as I am packaging this for Nix.

**Comment by lmcinnes** [comment]
The cosine distance package was created by someone else who really wanted to work with cosine distance. Their work was eventually folded into this library. The normal variant is the one you want, and the cosine variant should be considered deprecated (it has not been kept up to date with many other features and bug fixes).

**Comment by ixxie** [comment]
@lmcinnes thanks for the clarification!
