### ISSUE TITLE
How to avoid distance matrix computation?

### ISSUE THREAD

**Issue by mattyd2** [scikit-learn-contrib/hdbscan#199]
Hello,

When I attempt to load a pre-computed distance matrix for HDBSCAN, the `fit()` call still runs as though I'm doing it for the first time.

```
import hdbscan
import multiprocessing

hdbs = hdbscan.HDBSCAN(
    min_cluster_size=20,
    min_samples=40,
    metric="euclidean",
    alpha=1.0,
    p=None,
    memory="/path_to_memory_dir/",
    algorithm="best",
    leaf_size=40,
    approx_min_span_tree=True,
    gen_min_span_tree=False,
    core_dist_n_jobs=multiprocessing.cpu_count(),
    cluster_selection_method="eom",
    allow_single_cluster=False,
    prediction_data=False,
    match_reference_implementation=False)

hdbs.fit(blobs)
```

Not sure what I'm doing wrong, but any guidance would be appreciated, and I'm happy to make a tutorial of it afterwards.

Thanks,

**Comment by mattyd2** [comment]
@lmcinnes It turned out that this was a permissions issue on my server that would not allow hdbscan to create new directories for each distance matrix it computes. It would be nice is this cause a Warning or Error. Happy to help add it if you give me some pointers on where it belongs.

**Comment by mdunnlp** [comment]
@lmcinnes Sorry to re-open this issue, but I'm running into the same issue again. I've checked the permissions of the directory and they are completely open, so I'm unclear why it keeps recomputing the distance matrix.

Any ideas?

**Comment by lmcinnes** [comment]
No need to apologise -- if it isn't working that's an issue. I admit I'm not too clear on the details of what could be going wrong here. You mention distance matrices, but ideally hdbscan should never be computing distance matrices. Instead we should be caching the single linkage tree associated to a fixed ``min_samples`` value. From my understanding of joblib it uses some hashing tricks to compare input arrays and then load from cache if the input is identical, saving the recomputation. It sounds as if that is not working, but I don't quite know why that should be the case. It may be worth checking if it generates the same single linkage tree each time (i.e. copy the cached files out and then compare when it reruns and regenerates the cached data). If not then there is something strange afoot; if it is then somehow joblib is not recognising the identical input.

**Comment by mdunnlp** [comment]
@lmcinnes we went through it again and we think the code is working properly where it's loading from the precomputed single linkage tree. So, I think this can be closed, but I would offer to make the documentation much more explicit about what hyperparameters result in the recomputation of the single linkage tree. If you feel like this would be helpful, please let me know and I'll make a pull request on an update to the docs.

**Comment by lmcinnes** [comment]
Absolutely -- I haven't had much time to work on hdbscan docs recently, but this is definitely one of the topics I meant to eventually get to. If you have the time and inclination to write something sensible I will more than happily merge it in. Thanks!
