### ISSUE TITLE
Optimizing HDBSCAN for huge datasets

### ISSUE THREAD

**Issue by Karvi95** [scikit-learn-contrib/hdbscan#212]
Hi! Thank you very much for this innovative algorithm; heretofore have gotten a lot of mileage out of it and the accompanying well-written docs.

I'm attempting to cluster a dataset of shape: (8870443, 2); it's basically an numpy array of lat/longs converted into radians.

The corresponding code looks like:
```
import hdbscan
from joblib import Memory
mem = Memory(cachedir='/tmp/joblib')`

InRadians = np.radians(df[['lat', 'lon']])
data = np.array(InRadians)

clusterer = hdbscan.HDBSCAN(metric='haversine', min_cluster_size=3, algorithm='prims_balltree', core_dist_n_jobs=8, memory=mem).fit(data) 
```
.

This hasn't finished even though it's been running for 3 hours.

I have read Issue https://github.com/scikit-learn-contrib/hdbscan/issues/27 but because I'm using the haversine metric I had to switch the algorithm from 'prims_kdtree' to be 'prims_balltree'. The other useful part of that thread was including the core_dist_n_jobs which I set to 8. Other than that though, I haven't been able to find anything to resolve my problem.

Is this there anything more that I could do to speed up the performance (short of upgrading hardware)?

Hardware Specs:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299
Processor(s):               Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~802 Mhz
Total Physical Memory:     16,239 MB
Available Physical Memory: 5,646 MB
Virtual Memory: Max Size:  21,359 MB
Virtual Memory: Available: 8,495 MB
Virtual Memory: In Use:    12,864 MB

I tried attaching the file in the comment but it exceeds 10MB...

UPDATE: 
It finished; here's the stack trace:
```
[Memory] Calling hdbscan.hdbscan_._hdbscan_prims_balltree...
_hdbscan_prims_balltree(array([[ 0.830357, -2.132278],
       ...,
       [ 0.831464, -2.131725]]), 1000, 1.0, 'haversine', None, 40, False)
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-5-b1938e51c86b> in <module>()
      8 #### 5. Extract the stable clusters from the condensed tree.
      9 
---> 10 clusterer = hdbscan.HDBSCAN(metric='haversine', min_cluster_size=3, min_samples=1000, algorithm='prims_balltree', core_dist_n_jobs=8, memory=mem).fit(data)
     11 labels = clusterer.labels_

c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\hdbscan\hdbscan_.py in fit(self, X, y)
    814          self._condensed_tree,
    815          self._single_linkage_tree,
--> 816          self._min_spanning_tree) = hdbscan(X, **kwargs)
    817 
    818         if self.prediction_data:

c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\hdbscan\hdbscan_.py in hdbscan(X, min_cluster_size, min_samples, alpha, metric, p, leaf_size, algorithm, memory, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, cluster_selection_method, allow_single_cluster, match_reference_implementation, **kwargs)
    496                 _hdbscan_prims_balltree)(X, min_samples, alpha,
    497                                          metric, p, leaf_size,
--> 498                                          gen_min_span_tree, **kwargs)
    499         elif algorithm == 'boruvka_kdtree':
    500             if metric not in BallTree.valid_metrics:

~\AppData\Roaming\Python\Python36\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    560 
    561     def __call__(self, *args, **kwargs):
--> 562         return self._cached_call(args, kwargs)[0]
    563 
    564     def __reduce__(self):

~\AppData\Roaming\Python\Python36\site-packages\joblib\memory.py in _cached_call(self, args, kwargs)
    508                           'directory %s'
    509                         % (name, argument_hash, output_dir))
--> 510             out, metadata = self.call(*args, **kwargs)
    511             if self.mmap_mode is not None:
    512                 # Memmap the output at the first call to be consistent with

~\AppData\Roaming\Python\Python36\site-packages\joblib\memory.py in call(self, *args, **kwargs)
    742         if self._verbose > 0:
    743             print(format_call(self.func, args, kwargs))
--> 744         output = self.func(*args, **kwargs)
    745         self._persist_output(output, output_dir)
    746         duration = time.time() - start_time

c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\hdbscan\hdbscan_.py in _hdbscan_prims_balltree(X, min_samples, alpha, metric, p, leaf_size, gen_min_span_tree, **kwargs)
    205     core_distances = tree.query(X, k=min_samples,
    206                                 dualtree=True,
--> 207                                 breadth_first=True)[0][:, -1].copy(order='C')
    208 
    209     # Mutual reachability distance is implicit in mst_linkage_core_vector

sklearn\neighbors\binary_tree.pxi in sklearn.neighbors.ball_tree.BinaryTree.query()

sklearn\neighbors\binary_tree.pxi in sklearn.neighbors.ball_tree.NeighborsHeap.__init__()

MemoryError: 
```

**Comment by lmcinnes** [comment]
The current hdbscan is not optimised for memory, and it seems you simply ran out of memory. That is a very large dataset, and it will certainly potentially take a few hours to finish, especially if memory is tight and it starts swapping. Ultimately I think you would need a machine with more RAM; I don't think there are any ways around that. Sorry.

**Comment by Karvi95** [comment]
Understood; just wanted to figure out if there was anything else I could do with the current config. Thanks!

**Comment by sharma-ji** [comment]
Hey I am having the same issue, my system has 31 GB of usable RAM.
My data has `(186219,15)` shape. 
I am skeptical about the minimum cluster size. As I need to have around 20 clusters, so I am using 9000 as `min_cluster_size`.
Can you please give your opinion over it.

**Comment by lmcinnes** [comment]
If you don't specify ``min_samples`` independently of ``min_cluster_size`` it will default to using a ``min_samples`` value the same as the ``min_cluster_size``. A ``min_samples`` value of 9000 is potentially going to cause real problems for you. Instead consider something more like:

```python
clusterer = hdbscan.HDBSCAN(min_cluster_size=9000, min_samples=10)
clusterer.fit(data)
```
