### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mashuklya** [scikit-learn-contrib/hdbscan#216]
Could you please share your dataset `clusterable_data.npy` from http://hdbscan.readthedocs.io/en/latest/comparing_clustering_algorithms.html ?

**Comment by lmcinnes** [comment]
Thanks for the interest. The data is available in the github repo under notebooks. Alternatively you can fetch it from [this link](https://github.com/scikit-learn-contrib/hdbscan/blob/master/notebooks/clusterable_data.npy?raw=true).
