### ISSUE TITLE
How can I set up the k value in HDBSCAN class that could compute points' core distance?

### ISSUE THREAD

**Issue by OseongKwon** [scikit-learn-contrib/hdbscan#227]
At 'Transform the space' section in 'How HDBSCAN Works' document, you said:
the core distance defined for parameter k for a point x and denote as \mathrm{core}_k(x).

But I couldn't  find the k parameter in the HDBSCAN class, But in the RobustSingleLinkage class.
However, don't HDBSCAN use RobustSingleLinkage!

**Comment by lmcinnes** [comment]
The relevant parameter for hdbscan is ``min_samples``, following the naming
coventions of sklearn's ``DBSCAN`` class.

**Comment by OseongKwon** [comment]
Thanks! good.
