### ISSUE TITLE
Clustering on the outliers

### ISSUE THREAD

**Issue by rtmatx** [scikit-learn-contrib/hdbscan#255]
Hi,

Thanks a lot for the library. I have been using it regularly and have few questions about some of the things that I noticed on the results. I noticed this behavior over several datasets that I experimented with.

I start with clustering a huge dataset on 20-ish features. I get ~40 clusters and ~5% of them are called as outliers/anomalies. But I want to reduce the number of outliers or try to group them.  

The way I do grouping for identifying consistent outliers/anomalies is by maintaining all the initial clusterer settings but reducing the `min_cluster_size` (lets say by half), let's say that as second_min_cluster_size,  and then clustering just on the outliers. That way, I am hoping to identify few groups that couldn't form as clusters (because of min_cluster_size) and ended up as anomalies. 

The second clustering generates lot less outliers and few cluster groups which are spread all over.  Some of the cluster groups have lot of observations, some times 10 times more than the first_min_cluster_size. If it could form such a big cluster, then shouldn't it have been formed in the first place with first_clusterer settings?

Sorry if my question sounds too confusing, my intention is to use the clusters for some information but also reduce the anomalies by grouping them as consistent anomalies so that I will have few anomaly groups and less number of anomalies at the end of the second step

Thanks

**Comment by lmcinnes** [comment]
To understand what is going on I would suggest you look at the [condensed tree plots](https://hdbscan.readthedocs.io/en/latest/advanced_hdbscan.html#condensed-trees) of each of the clusterings. I suspect that the smaller ``min_cluster_size`` causes the large clusters to shatter earlier, thus making the large clusters look more appealing to the cluster selection method.
