### ISSUE TITLE
scipy kmeans vs sklearn kmeans performance

### ISSUE THREAD

**Issue by Willyees** [scikit-learn-contrib/hdbscan#285]
[https://github.com/scikit-learn-contrib/hdbscan/blob/master/docs/performance_and_scalability.rst](url)
At the end of the doc is specified how the sklern implementation is superior to the scipy based on the time registered. 
"Finally it demonstrates again how much of a difference implementation can make: the sklearn implementation of K-Means is far better than the scipy implementation"
I think it should be mentioned that using default settings for the two implementations, the number of iterations is different. sklearn 10, scipy 20
[https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans.html#scipy.cluster.vq.kmeans](url)

**Comment by lmcinnes** [comment]
Thanks -- you are more than welcome to add a pull request for it.
