### ISSUE TITLE
all_points_membership_vectors and membership_vectors return nan probabilities

### ISSUE THREAD

**Issue by alberto-sibner** [scikit-learn-contrib/hdbscan#295]
Hi,

I'm using hdbscan with haversine metric to find clusters based on latitudes and longitudes. The algorithm works really well for me. However, when I use `all_points_membership_vectors `and `membership_vectors` with some coordinates these methods return nan probabilities.

In other words, I have N points in my dataset and they are all classified quite well using soft clustering. Although for a small part of these N points I get NAN probabilities of them belonging to any of the clusters. 

I have checked some of these points individually and they seem totally normal for me, they are surrounded by a lot of clusters in the map and yet they don't have probabilities of belonging to any of them.

**Comment by alberto-sibner** [comment]
Any ideas about in which situations this might happen?

Thank you very much

**Comment by alberto-sibner** [comment]
Hi @lmcinnes 

Any ideas about why this might be happening?

Thanks in advance

**Comment by lmcinnes** [comment]
At this point I must admit that I am not sure quite why the soft cluster membership functions fail -- it has been a while since I wrote them, and there seem to be odd corner cases that trigger behaviour, but I can rarely reproduce it, so while  afew things have been fixed, niggling issues remain, for which I don't really have any ideas.

**Comment by alberto-sibner** [comment]
@lmcinnes Oh, I see what you mean... Fair enough! Do you think I could help you fixing this issue? Soft clustering is very important for the problems I need to solve and hdbscan is the algorithm that work best for me after having tried a lot.

I have the exact parameters that trigger this behaviour for the dataset I use (and also a trained model if you want). Could I share them with you privately and help you debugging this?

Thank you very much!

**Comment by alberto-sibner** [comment]
I've managed to solve it. In my case, it seems the problem was due to having a few points duplicated in the long lists I wanted to find clusters in.
