### ISSUE TITLE
Persistence score and labels

### ISSUE THREAD

**Issue by earikan** [scikit-learn-contrib/hdbscan#302]
Hi,

I want to know which labels in the cluster that has been given the persistent score. 

For example, as a result of cluster_persistence_ ,
    Out[34]:
    array([ 0.35, 0.2 , 0.44, 0.23 , 0.16 , 0.44, 0.02])

How can I learn the labels of cluster with a persistence score of 0.35? Is it possible?

Thanks.

**Comment by chaturv3di** [comment]
There should be a one-to-one correspondence between the persistence scores and the output of `numpy.unique(clusterer.labels_)`.
