### ISSUE TITLE
Not using all available CPUs?

### ISSUE THREAD

**Issue by scribu** [scikit-learn-contrib/hdbscan#310]
Hi,

I'm running the following algorithm on 100K samples, using a machine with 16 cores:

```python
clusterer = HDBSCAN(
    algorithm='boruvka_balltree',
    core_dist_n_jobs=16,
)
```

Behaviour:

1. First few seconds: Uses 16 cores.
2. Next few minutes: Uses 4 cores.
3. Remaining time: Uses 1 core.

I would expect stage 2 to also use 16 cores.

Is there another parameter I need to pass in order to use all cores?

Note that `cpu_count()` correctly returns 16 as well.

Using hdbscan 0.8.22

**Comment by lmcinnes** [comment]
Only the core distance computation can use all the cores, sadly that is apparently the first few seconds. The rest of the computation is quite challenging to parallelise unfortunately and will run on a single thread.

**Comment by scribu** [comment]
But if the later stages are single threaded, how come I still see *4* cores being used? 🤔

**Comment by lmcinnes** [comment]
That I'm not really sure of -- there are some aspects that might be getting parallelised by the backend libraries.

**Comment by GorvinChen** [comment]
Is there anything wrong with _hdbscan_boruvka.so? I see only 4 cores being used too.
