### ISSUE TITLE
How make approximate_predict with precomputed distances 

### ISSUE THREAD

**Issue by JevgeniyVnk** [scikit-learn-contrib/hdbscan#314]
Hello.
I want to use Gower distance. For this I precompute pairwise distances between points and fit hdbscan model. But in a future I need to classify new points (approximate_predict + fited model).
How can I do this? Yes, compute distances between "old" and new points, but how to make prediction on this new distances? 
Now, if Im trying to make predictions like this:

`clustering_model = hdbscan.HDBSCAN(metric='precomputed',prediction_data=True)
clusters = clustering_model.fit_predict(gower_dist_matrix)
hdbscan.approximate_predict(clustering_model,gower_dist_matrix)`

get error:
`AttributeError: No prediction data was generated`

Thanks. Sorry for bad English.

**Comment by lmcinnes** [comment]
I don't believe the prediction approach supports custom/precomputed metrics at this time. Sorry.

**Comment by JevgeniyVnk** [comment]
Thanks for answer. Anyway your implementation of hdbscan very usefull and docs are great.

**Comment by leo83** [comment]
Hi! Is there any progress on this issue? And do you have plans to support approximate_predict with precomputed distances ever ?

**Comment by jhindel** [comment]
I agree, will this be available in the future?
