### ISSUE TITLE
pip install fail--CANNOT Building wheels for Hdbscan Windows 

### ISSUE THREAD

**Issue by mengxibai** [scikit-learn-contrib/hdbscan#318]
I had visual studio community 2019 on windows and setted environment variable for cl.exe. But there is still an exist error 2 for cl.exe. 
Already had cython.
Please help. 

  Building wheel for HDBSCAN (PEP 517) ... error
   ERROR: Command errored out with exit status 1:
   command: 'c:\users\NAME\desktop\python 3.7.2\python.exe' 'c:\users\NAME\desktop\python 3.7.2\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\NAME\AppData\Local\Temp\tmpa8byq2e5'
       cwd: C:\Users\NAME\AppData\Local\Temp\pip-install-z0y595n7\HDBSCAN
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\hdbscan
  copying hdbscan\hdbscan_.py -> build\lib.win-amd64-3.7\hdbscan
  copying hdbscan\plots.py -> build\lib.win-amd64-3.7\hdbscan
  copying hdbscan\prediction.py -> build\lib.win-amd64-3.7\hdbscan
  copying hdbscan\robust_single_linkage_.py -> build\lib.win-amd64-3.7\hdbscan
  copying hdbscan\validity.py -> build\lib.win-amd64-3.7\hdbscan
  copying hdbscan\__init__.py -> build\lib.win-amd64-3.7\hdbscan
  creating build\lib.win-amd64-3.7\hdbscan\tests
  copying hdbscan\tests\test_hdbscan.py -> build\lib.win-amd64-3.7\hdbscan\tests
  copying hdbscan\tests\test_rsl.py -> build\lib.win-amd64-3.7\hdbscan\tests
  copying hdbscan\tests\__init__.py -> build\lib.win-amd64-3.7\hdbscan\tests
  running build_ext
  cythoning hdbscan/_hdbscan_tree.pyx to hdbscan\_hdbscan_tree.c
  building 'hdbscan._hdbscan_tree' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\hdbscan
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-Ic:\users\NAME\desktop\python 3.7.2\include" "-Ic:\users\mengxi bai\desktop\python 3.7.2\include" -IC:\Users\NAME\AppData\Local\Temp\pip-build-env-b1hyxd4u\overlay\Lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" /Tchdbscan\_hdbscan_tree.c /Fobuild\temp.win-amd64-3.7\Release\hdbscan\_hdbscan_tree.obj
  _hdbscan_tree.c
  c:\users\NAME\desktop\python 3.7.2\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  C:\Users\NAME\AppData\Local\Temp\pip-build-env-b1hyxd4u\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\NAME\AppData\Local\Temp\pip-install-z0y595n7\HDBSCAN\hdbscan\_hdbscan_tree.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for HDBSCAN
  Running setup.py clean for HDBSCAN
Failed to build HDBSCAN
ERROR: Could not build wheels for HDBSCAN which use PEP 517 and cannot be installed directly

**Comment by mengxibai** [comment]
Solved

**Comment by shenaha** [comment]
@mengxibai , I am facing the same problem would like to know how you solved it ?

**Comment by mengxibai** [comment]
Sorry, I do not remember how I solved this issue. But you can try to download hdbscan.py from the attachment and put it directly to where your python is installed and see if it will help.&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by shenaha** [comment]
Thanks a lot will try it.
