### ISSUE TITLE
Merge clusters based on condensed tree representation

### ISSUE THREAD

**Issue by rtmatx** [scikit-learn-contrib/hdbscan#328]
Hi,

Can we use the condensed tree representation that is available from `hdbscan` and the information related to `parent` and `child` cluster labels to merge clusters.

**Comment by lmcinnes** [comment]
That is certainly a reasonable approach.

**Comment by rtmatx** [comment]
Thanks. I have implemented using the `parent` and `child` cluster labels 👍
