### ISSUE TITLE
Not able to pass "cluster_selection_epsilon" argument

### ISSUE THREAD

**Issue by nish10** [scikit-learn-contrib/hdbscan#340]
Getting following error 

TypeError: __init__() got an unexpected keyword argument 'cluster_selection_epsilon'

**Comment by SansMorel** [comment]
I had the same issue. Reinstalling from github worked for me. 

`pip install --upgrade git+https://github.com/scikit-learn-contrib/hdbscan.git#egg=hdbscan`

**Comment by nish10** [comment]
Thanks,

import hdbscan

clusterer = hdbscan.hdbscan_.HDBSCAN(min_cluster_size=2, metric='euclidean', cluster_selection_epsilon=0.2, cluster_selection_method = 'eom', prediction_data=True).fit(X)

also worked for me.

**Comment by bilbusra** [comment]
I get also the same error and I installed this with conda. Tried this with conda install but it didn't work.
