### ISSUE TITLE
Want to run HDBSCAN on multiple machines

### ISSUE THREAD

**Issue by olivatooo** [scikit-learn-contrib/hdbscan#347]
Anyone have any idea of how to achieve that?
There are any example of code/article that does that?
What parts can/cannot be parallelized?

I really need to execute HDBSCAN in a more efficient way, and I can contribute to achieve that

**Comment by lmcinnes** [comment]
Do you need a distributed algorithm or merely a parallel one? Also what is the dimensionality of the data you want to apply the algorithm to -- since that can have a significant effect on which approaches are best. Finally how much data are you wanting to apply this to -- how many total samples?

**Comment by olivatooo** [comment]
Thanks for answering! =D

**Data:** I have about ~100k samples and 26 dimensions.

**Do you need a distributed algorithm or merely a parallel one?** 
I want to execute in a fast way, parallel or distributed, don't matter. After reading the issues I see multiple people wanting to run `parallel`, and the answer always is `it's a non trivial problem`. Maybe I can help if I a have a north.

**Problem:** I want to find the best `min_cluster_size` and the best `min_samples` so I'm brute forcing all possible values in a big range and checking the `relative_validity_`(this is very slow). This is why I want a parallel or a distributed execution. I see a naive approach, executing this brute force in multiple cores/machines, but I don't know if this is the better solution

I already search for a RNG HDBSCAN* implementation, to find these values, but I didn't find any implementation =/

**Comment by lmcinnes** [comment]
So what you want is possible, but not implemented anywhere that I know of (aside from something along the right lines in the LargeVis R package oddly enough). I think you could potentially implement something decent using pynndescent for the heavy lifting, but it would definitely take some implementation work. Something along these lines has been on my TODO for some time, but I have had too many things that keep jumping to a higher priority. If you are interested email me and I can outline what the code would need to do.

**Comment by olivatooo** [comment]
Sure!! How can I contact you? I looked through your github but I didn't find any contact info

**Comment by lmcinnes** [comment]
You can reach me at leland.mcinnes@gmail.com
