### ISSUE TITLE
Build fails with " hdbscan\dist_metrics.c(11558): error C2065: 'M_PI': undeclared identifier"

### ISSUE THREAD

**Issue by sk1p** [scikit-learn-contrib/hdbscan#380]
See an example detailed log here:

https://ci.appveyor.com/project/sk1p/libertem/builds/32981335/job/6yet7c9kntx1381r

I'm not sure why this is happening - possibly the build environment changed on AppVeyor?

**Comment by imatiach-msft** [comment]
seeing this issue in our builds and in production, is there any workaround?

**Comment by imatiach-msft** [comment]
seems like a bug in dist_metrics.c:
https://stackoverflow.com/questions/26065359/m-pi-flagged-as-undeclared-identifier

**Comment by sk1p** [comment]
See also this cython issue: https://github.com/cython/cython/issues/3622

**Comment by imatiach-msft** [comment]
somehow the issue self-resolved, I do see a new cython was published on pypi, hope it doesn't appear again

**Comment by sk1p** [comment]
> a new cython was published on pypi

Yeah, seems like a typo found it's way into the cython release. All okay now!
