### ISSUE TITLE
max_cluster_size option?

### ISSUE THREAD

**Issue by Rocketknight1** [scikit-learn-contrib/hdbscan#408]
Hi, I've been using HDBSCAN for a while, particularly for document clustering with word mover or word embedding distances. It's been great, but one thing I've noticed is that there's a tendency, even when allow_single_cluster is disabled, for the data to end up lumped together into one big blob, with a small number of tiny clusters off to the side. This might be because my distances are a bit pathological, but when this happens I can usually recover it by switching to leaf clustering or just recursing into the single blob. 

A quick workaround that would be very useful here would be to have a 'max_cluster_size' argument, which I could set to say 25% or 50% of my dataset size, and that would guarantee that the EOM clusterer would not consider clusters over that size. This should be pretty easy to implement, and it's a very intuitive setting for people to use, like min_cluster_size, that does not require them to deeply understand the HDBSCAN internals.

If this is interesting, would you like me to try to hack it in myself and submit a PR, or is this something you'd prefer not to have in HDBSCAN?

**Comment by lmcinnes** [comment]
I agree that this would potentially be useful. I don't think it would be too hard to allow for this in the EOM algorithm as it stands. I would certainly welcome a PR and work with you on it if you wanted to have a go at implementing it.

**Comment by Rocketknight1** [comment]
I'll try! Do you think it should fully replace the allow_single_cluster option, or is it worth keeping both?

**Comment by lmcinnes** [comment]
I would keep both for now; depending on how things look we can deal with that later.

**Comment by Rocketknight1** [comment]
It seems like I might be able to just slightly modify traverse_upwards() in [flat.py](https://github.com/scikit-learn-contrib/hdbscan/blob/master/hdbscan/flat.py#L907-L922) and [_hdbscan_tree.pyx](https://github.com/scikit-learn-contrib/hdbscan/blob/master/hdbscan/_hdbscan_tree.pyx#L615-L629), but it's not quite as simple as the case for allow_single_cluster because the function needs to have some idea of how many samples are children of the given node.

Is there an efficient way to get that information from inside that function? If so, then this should be a fairly quick process, though I realize that naively recomputing it in every call to traverse_upwards() might be quite redundant.

**Comment by lmcinnes** [comment]
Yes -- I think you would want a modified version of that function that accumulates the total size of the cluster as you go.

**Comment by Rocketknight1** [comment]
One final question: How should max_cluster_size interact with cluster_selection_epsilon? It's probably unlikely in practice with reasonable values, but there's an edge case where the cluster_selection_epsilon parameter would ordinarily cause a merge, but this would create a cluster larger than max_cluster_size.

I'm guessing max_cluster_size should take priority in this case, but I think either should be possible to code.

**Comment by lmcinnes** [comment]
I think it is okay for cluster selection epsilon to take priority, especially if that makes the coding easier and simpler (simpler code is definitely better for long term maintenance). The best thing to do to mitigate that is ensure there is some documentation in the docstring for the ``max_cluster_size`` parameter that this can occur.

**Comment by Rocketknight1** [comment]
Closing this issue as discussion is now taking place in pull request #410
