### ISSUE TITLE
cluster_selection_epsilon does not merge noise at root level

### ISSUE THREAD

**Issue by neontty** [scikit-learn-contrib/hdbscan#417]
Looking at Danielzgtz 's original question at [#370](https://github.com/scikit-learn-contrib/hdbscan/issues/370) he proposed:
> I am using those two options together to try and get the `no_structure` [toy dataset](https://scikit-learn.org/stable/auto_examples/cluster/plot_cluster_comparison.html) (bottom row, square) clustered properly. **I want the square to be completely blue like how DBSCAN does it**. When I only use `cluster_selection_epsilon`, multiple clusters appear in that square. When I only use `allow_single_cluster=True`, **part of that square is grey**. I think I can only get the desired result using both of those arguments, but HDBSCAN crashes when I do that.

After fixing the crash issue, we have not addressed his true goal. 

I agree with daniel that if ```cluster_selection_epsilon``` is a very large number (larger than [1 / root's lambda value]) HDBSCAN should return all points as the same label. However, currently it keeps all child_size==1 leaves of the root node as noise. 

Based on the paper by baum / @cmalzer it seems like this is violating the "act like DBSCAN" for items in single linkage tree below epsilon. 

I believe the fix would be to change ```do_labelling``` [_hdbscan_tree.pyx:459-460](https://github.com/scikit-learn-contrib/hdbscan/blob/97a4dcf561111c770578cdb6e70c602c4504942b/hdbscan/_hdbscan_tree.pyx#L459)  with

```
if len(clusters) == 1 and allow_single_cluster and \
                tree['lambda_val'][tree['child'] == n] >= 1 / cluster_selection_epsilon :
```

Do the maintainers agree with this fix?

Edit: I could have put this in the pull #400 but I think that was focused on the index OOB errors and this is a bit of a separate issue.

**Comment by cmalzer** [comment]
I think that's fine in general; I would just change double to `np.double_t cluster_selection_epsilon` and add an `elif` clause where we also check if we actually have an epsilon > 0.  Something like this:

```
if len(clusters) == 1 and allow_single_cluster and \
                tree['lambda_val'][tree['child'] == n] >= \
                    tree['lambda_val'][tree['parent'] == cluster].max():
                result[n] = cluster_label_map[cluster]
            elif  len(clusters) == 1 and allow_single_cluster and \
                cluster_selection_epsilon > 0 and \
                    tree['lambda_val'][tree['child'] == n] >= 1/cluster_selection_epsilon:
              [tree['child'] == n], 1/cluster_selection_epsilon))
                result[n] = cluster_label_map[cluster]
            else: ...
```

**Comment by neontty** [comment]
Haha, I realized I forgot the main case right after I opened the issue. The pull has the right commits in it. I will change the argument to a np.double_t though.

Here's what the conditionals look like in the PR
```
      elif cluster == root_cluster:
            if len(clusters) == 1 and allow_single_cluster:
                if cluster_selection_epsilon != 0.0:
                    if tree['lambda_val'][tree['child'] == n] >= 1 / cluster_selection_epsilon :
                        result[n] = cluster_label_map[cluster]
                    else:
                        result[n] = -1
                elif tree['lambda_val'][tree['child'] == n] >= \
                     tree['lambda_val'][tree['parent'] == cluster].max():
                    result[n] = cluster_label_map[cluster]
                else:
                    result[n] = -1
            else:
                result[n] = -1
```
