### ISSUE TITLE
Keyerror in validity_index()

### ISSUE THREAD

**Issue by 79shreya** [scikit-learn-contrib/hdbscan#441]
I am trying to implement density-based clustering on a dataset using HDBSCAN. I am reducing the dimensionality of the dataset using PCA before fitting the model. And then I am trying to calculate validity index of the model to see how well it performed. This is my code:

model= hdbscan.HDBSCAN(min_cluster_size=int(0.015*pca_components.shape[0]), min_samples=1 )
model.fit(pca_components)
clusters = model.labels_
print("validity index: ",hdbscan.validity_index(pca_components, clusters))

But it throws this error while calculating validity index:

\lib\site-packages\hdbscan\validity.py in validity_index(X, labels, metric, d, per_cluster_scores, **kwd_args)
    329 
    330         mr_distances, core_distances[
--> 331             cluster_id] = all_points_mutual_reachability(
    332             X,
    333             labels,

\lib\site-packages\hdbscan\validity.py in all_points_mutual_reachability(X, labels, cluster_id, metric, d, **kwd_args)
    100         distance_matrix = X[labels == cluster_id, :][:, labels == cluster_id]
    101     else:
--> 102         subset_X = X[labels == cluster_id, :]
    103         distance_matrix = pairwise_distances(subset_X, metric=metric,
    104                                              **kwd_args)

\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2900             if self.columns.nlevels > 1:
   2901                 return self._getitem_multilevel(key)
-> 2902             indexer = self.columns.get_loc(key)
   2903             if is_integer(indexer):
   2904                 indexer = [indexer]

\lib\site-packages\pandas\core\indexes\range.py in get_loc(self, key, method, tolerance)
    356                 except ValueError as err:
    357                     raise KeyError(key) from err
--> 358             raise KeyError(key)
    359         return super().get_loc(key, method=method, tolerance=tolerance)
    360 

KeyError: (array([ True, False, False, ...,  True, False, False]), slice(None, None, None))
 
Any idea why this might be happening?

**Comment by madnessInAction** [comment]
Was there any resolution to this? I've verified that the X and labels don't have any nan's and I'm getting the same result.

**Comment by DanielTamayo22** [comment]
I managed to make it work by passing the np array X.values instead of the whole dataframe X to the validity_index function
