### ISSUE TITLE
Speed Issues (DBSCAN much faster (10 sec), HDBSCAN didn't finish after 30min))

### ISSUE THREAD

**Issue by lagmoellertim** [scikit-learn-contrib/hdbscan#444]
Hey,
I don't know if I'm doing anything wrong, but I tried to run 35000 datapoints with 128d through HDBSCAN, but it didn't seem to finish, even after 30 mins, so I stopped it (but no exception was thrown and there was no other output from HDBSCAN). I tried it on my Windows PC and on Google Colab, neither worked [Colab Link](https://colab.research.google.com/drive/1Et_DP4J2dyGJntggGZ1sRTVXw9T7btYw?usp=sharing). DBSCAN finished the whole operation in 10 seconds.

Can you help me? Thanks in advance 👍

**Comment by lmcinnes** [comment]
DBSCAN runtime can be pretty sensitive to parameters. If you run with a small enough ``epsilon`` (and small enough varies by dataset) then it can complete almost instantly by simply declaring almost every sample noise. On the other hand you can also choose an overly large ``epsilon`` and grind DBSCAN to a halt. I would therefore be a little careful about reading too much into the DBSCAN runtime unless you've tuned ``epsilon`` first (or checked the resulting clusters).

For HDBSCAN you'll want a smaller dimension to get decent runtimes. You can use a dimension reduction technique to achieve this. Either PCA to, say, 20 dimensions, or UMAP to 3 or 4 dimensions, might be a good preprocessing step.
