### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by gansanay** [scikit-learn-contrib/hdbscan#448]
HDBSCAN doesn't build because of various problems:
* tests use sklearn.utils testing methods that have been moved/removed
* `test_hdbscan_approximate_predict_score()` cannot catch warnings that are not triggered because of a lacking warnings filter configuration

Will provide a PR fixing the build before looking at anything else.

**Comment by gansanay** [comment]
Plus, scikit-learn now requires Python 3.6 or newer, so building on Python 3.5 may be dropped.

**Comment by lmcinnes** [comment]
Thanks for the fix!
