### ISSUE TITLE
approximate_predict always returning 0 for probability

### ISSUE THREAD

**Issue by JZafar1** [scikit-learn-contrib/hdbscan#452]
I am using HDBSCAN to generate prediction data. I then attempt to classify new points using the `approximate_predict` function to find the correct cluster for a new point. The model returns the correct cluster for a new point but the probability/strength is always 0.0. To generate the model and classify new points I use:

```python
# Generate the model
cluster_model = hdbscan.HDBSCAN(metric='euclidean', min_cluster_size=3, cluster_selection_epsilon=0.4,
                                prediction_data=True).fit(data)

# Classify new point
cluster, prob = hdbscan.approximate_predict(cluster_model, new_point)
print(cluster, probability)
```

As I understand, if the strength/probability is 0.0 the point has been classified as noise. From manual analysis of the new points I can see they do fit into the heart of the original clusters so I don't understand why the probability is always 0.0? Is this a potential problem with the algorithm, the model I am using to generate or am I missing something else?

**Comment by gansanay** [comment]
Hi @JZafar1,

It is difficult to give you any precise answer because it highly depends on your data. Can you share a full example with fake data or a generic online dataset?

The following code, inspired by sample code from scikit-learn, reproduces your task but gives me some nonzero probabilities. 

Does it also work for you, giving some nonzero probabilities?

Please also be aware that you are printing the `probability `variable and you computed the `prob` variable with `approximate_predict`.

Regards,
Guillaume

```python
import numpy as np

import hdbscan
from sklearn import metrics
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler

# Generate training data
centers = [[1, 1], [-1, -1], [1, -1]]
X, labels_true = make_blobs(n_samples=750, centers=centers, cluster_std=0.4,
                            random_state=0)

X = StandardScaler().fit_transform(X)

X_train = X[:int(0.9*len(X))]
X_pred = X[int(0.9*len(X)):]

# Compute HDBSCAN
hdb = hdbscan.HDBSCAN(min_samples=10, prediction_data=True).fit(X_train)
core_samples_mask = np.zeros_like(hdb.labels_, dtype=bool)
labels = hdb.labels_

cluster, prob = hdbscan.approximate_predict(hdb, X_pred)

print('prob min: {:.2f}\nprob mean: {:.2f}\nprob max: {:.2f}'.format(prob.min(), prob.mean(), prob.max()))
```

**Comment by JZafar1** [comment]
@gansanay Thank you for the information, upon further investigation it was an issue with the data I was using to build the model, I appreciate your help with this matter.
