### ISSUE TITLE
Does not scale even with small dimensions

### ISSUE THREAD

**Issue by leoliu0** [scikit-learn-contrib/hdbscan#453]
Dear hdbscan developers,

I got to know the scaling performance is heavily impacted by input dimensions (Documentation says 50-100 is good). However, it does not scale in my case even I have 25 or 50. It stucks at 4 processes, which is the default value of core_dist_n_jobs. I use all default value for the HDBSCAN class. Is there a way to get the scaling??

**Comment by lmcinnes** [comment]
In the context used in the docs and discussions of "scaling" the scaling refers to performance changes with respect to dataset size -- larger datasets can produce significantly larger runtimes for many algorithms (say, for example, runtimes increases quadratically with respect to dataset size). In this sense HDBSCAN scales well (usually getting approximately O(N log N) scaling).

If you want to have multiple processors / threads engaged then I am afraid this kind of scaling is not available. Where possible HDBSCAN uses some tricks to get multicore use for those portions of the algorithm that are readily parallelizable, but the core of the algorithm is, unfortunately, fundamentally serial, and thus you will largely only be able to get single core performance.

**Comment by leoliu0** [comment]
Thanks for clarification
