### ISSUE TITLE
conda-forge osx-arm64 build

### ISSUE THREAD

**Issue by derinw** [scikit-learn-contrib/hdbscan#459]
Are there any plans to support the osx-arm64 platform through conda-forge?

**Comment by lmcinnes** [comment]
I'm not sure what it would take to make that happen; I would gladly accept PRs to the hdbscan-feedstock on conda-forge to make it possible.

**Comment by derinw** [comment]
Looks like a PR for migration required to conda-forge-pinning-feedstock, based on conda-forge knowledge base. I submitted the PR and will follow to completion. I don't believe any changes to hdbscan-feedstock will be required. https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1210#issue-572839436

**Comment by derinw** [comment]
Okay, looks like a bot will submit a PR automatically to hdbscan-feedstock in the near future

**Comment by lmcinnes** [comment]
Submitted and all green, so I merged it. Hopefully it works. Thanks so much for looking into this.

**Comment by derinw** [comment]
Successful conda install and import on python 3.8 and 3.9. Thanks!
