### ISSUE TITLE
Shared nodes between clusters

### ISSUE THREAD

**Issue by adminy** [scikit-learn-contrib/hdbscan#465]
HDBScan seems to be capable of producing clusters which share overlapping nodes, given that clustering for me is to identify shared points between clusters, what would I have to do to the algorithm to get those?

**Comment by lmcinnes** [comment]
HDBSCAN is a hierarchical clustering algorithm, and as such only produces strict hierarchies of clusters: if two clusters overlap it implies that one cluster is strictly contained within the other. It does not support overlapping clusters in the way I believe you want. To do that you would need a different algorithm altogether unfortunately, and I do not know of any particularly good clustering algorithms that support this kind of overlapping clusters.

**Comment by adminy** [comment]
mhm, thanks @lmcinnes
