### ISSUE TITLE
move to scikit-learn contrib?

### ISSUE THREAD

**Issue by amueller** [scikit-learn-contrib/hdbscan#47]
Hey.
Scikit-learn recently created a "contrib" repo to house related projects:
https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/README.md

The idea is to collect scikit-learn compatible algorithms in a single place, and provide more exposure.
It would be great to have hdbscan there, if you want to move the repo.

Best,
Andy

**Comment by lmcinnes** [comment]
I would be very happy to do that. I'll see if I can get that organised in the near future -- I have a lot of unrelated work in the near term so may not be able to get to it for a little while. Thanks for the invitation!

**Comment by amueller** [comment]
Cool :)
And no rush.
You should run the ``check_estimator`` function from the ``sklearn.utils.test_estimators`` module on all your classes. I think you fulfil all the other requirements.
