### ISSUE TITLE
Specifying 'cosine' as metric brings up error message

### ISSUE THREAD

**Issue by leszekmp** [scikit-learn-contrib/hdbscan#481]
Running HDBSCAN with the default 'euclidean' metric works fine. Most of the other defined distance metrics listed under sklearn.metrics.pairwise.PAIRWISE_DISTANCE_FUNCTIONS work as well (cityblock,haversine,l2,l1,manhattan).  But if I try to use 'cosine', I get the error message:

 ValueError: Unrecognized metric 'cosine'

**Comment by SergioG-M** [comment]
I'm having the same issue, any one knows what may be happening?

**Comment by Ejjaffe** [comment]
Having this issue too, no idea why it was closed. Here's my workaround:
```python
from scipy.spatial import distance
import hdbscan

# define X (n_samples, n_features)
mat = distance.cdist(X, X, metric='cosine')
hdb = hdbscan.HDBSCAN(metric='precomputed')
hdb.fit(mat)
```

**Comment by amezzali** [comment]
Hi, I have the same issue as well, with `hdbscan==0.8.27`, and I cannot use the workaround, due to the size of the table. Do you know if this will be solved soon?
thanks

**Comment by Ejjaffe** [comment]
Hdbscan needs to compute this table anyway I think, there's a slightly more efficient way to do it with:
```python
distance.squareform(distance.pdist(X, metric='cosine'))
```
Worst case scenario, you could use itertools to write to an array on your disk.
```python
import itertools as it
from scipy.spatial import distance


n = <length of array>
for i,j in it.combinations(range(n), r=2):
    # query storage for vectors i and j
    # open file for writing
    # write i,j and (j,i which is same as i,j) and (i,i , jj which are both 0)
```

**Comment by CholoTook** [comment]
Can I pre-compute the cosine distance matrix then use l2 ? Sorry, dumb question I know...
