### ISSUE TITLE
How to calculate clusters distance?

### ISSUE THREAD

**Issue by katzurik** [scikit-learn-contrib/hdbscan#544]
What will be a reasonable method to calculate the distance between clusters in order to find clusters that can be merged?

**Comment by lmcinnes** [comment]
If you want to find clusters to merge the best way is to analyze the condensed tree. You can access it as the ``condensed_tree_`` attribute, on which there are many methods, including ways to convert to numpy, pandas or networkX to be easier to work with. The ``select_clusters`` method on the tree will select out the cluster nodes in the tree that the cluster selection method found for your flat clustering.
