### ISSUE TITLE
While doing BERTopic modeling in hdbscan clustering step i am getting error as numpy.float64 cannot be interpreted as an integer

### ISSUE THREAD

**Issue by shubhambagalsrb** [scikit-learn-contrib/hdbscan#602]
in _hdbscan_tree.pyx  in condense_tree i am getting this error

**Comment by msfrazier** [comment]
Having this problem as well

**Comment by rulas99** [comment]
Having this problem as well

**Comment by mp-fernandes** [comment]
Me too

**Comment by mp-fernandes** [comment]
name = "hdbscan"
version = "0.8.29"

In this version I am not receiving this BUG.

**Comment by aquemy** [comment]
This should be solved by the newest version 0.8.33.
See in particular this message and the messages below: https://github.com/scikit-learn-contrib/hdbscan/issues/600#issuecomment-1640795484

**Comment by shubhambagalsrb** [comment]
Yeah I created new env and again installed all packages now it is working.
