### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by glemaitre** [scikit-learn-contrib/hdbscan#61]
I was wondering if you were interested to make the code following the PEP8 style.

I could take care of that if you are interested.

**Comment by lmcinnes** [comment]
I certainly won't mind if you want to fix it up. Hopefully it should be
fairly minor except for some naming (which follows sklearn conventions).

On Sat, Sep 3, 2016 at 7:48 AM, Guillaume Lemaitre <notifications@github.com
