### ISSUE TITLE
Error in `python': double free or corruption

### ISSUE THREAD

**Issue by whllnd** [scikit-learn-contrib/hdbscan#62]
Hi,

first, let me thank you for your work. It's been great to work with so far! Today I ran into a segmentation fault regarding a specific data set. It's available at https://userpage.fu-berlin.de/mdetlefsen/_dist_p10_new.csv (18mb, though). 

When loading the file and then wrapping the original 939x939 matrix into a 940x940 matrix, it runs fine. I played around with it for a while, but couldn't figure out anything more interesting. Sample code has been the following:

`dist = np.genfromtxt("_dist_p10_new.csv", delimiter=",")`
`clusterer = hdbscan.HDBSCAN(min_cluster_size=3, min_samples=3, metric='precomputed')`
`clusterer.fit(dist)`

Apart from this specific file, I haven't run into other problems so far. But I don't see the problem at first glance, since it's just another data file.

**Comment by lmcinnes** [comment]
It must be an odd corner case in the Cython. I'll try and track it down for
you when I get some time. Thanks for the report, and thanks also for a
dataset I can reproduce it with.

**Comment by lmcinnes** [comment]
I'm having trouble reproducing this on the systems I can test on -- I have python 3.5 on Mac and Python 2.7 on Linux. Both of those produce no errors when using master from the repository. Can you give me some more details about your setup and versions?

**Comment by whllnd** [comment]
It's python 3.5.2 on an Ubuntu 14.04 with hdbscan v0.8.1 installed via pip. Hope, it helps!

**Comment by lmcinnes** [comment]
I managed to reproduce, but it seems like this potentially got fixed since the 0.8.1 release -- can you verify that the current master from here works correctly for you?

**Comment by whllnd** [comment]
The current master works fine! Interestingly, the upgraded version (installed directly via github address) is also labeled 0.8.1, which is why I suggested, I'd already have the latest version. But then again, I have no clue, how pip handles its versioning. Anyway, problem fixed!

**Comment by lmcinnes** [comment]
Thanks!
