### ISSUE TITLE
requirements prevent cython>=3

### ISSUE THREAD

**Issue by HarrySoteriou** [scikit-learn-contrib/hdbscan#626]
There must some sort of misunderstanding because although there is a branch that addresses cython 3 compatibility; downloading the main branch, the latest 0.8.34 release or 0.8.33 that explicitly addresses cython 3 compatibility, cython is restricted to <=3 in requirements.txt.

Are there any failed test that prevent integration ?

**Comment by lmcinnes** [comment]
Cython 3 currently breaks things in ways that are hard to fix. It is simply easier to restrict to Cython < 3 for now.
