### ISSUE TITLE
issue with numy 2.0 `ValueError: numpy.dtype size changed`

### ISSUE THREAD

**Issue by RogerHYang** [scikit-learn-contrib/hdbscan#642]
screenshot below shows the error in Colab

```python
%pip install numpy==2.0 hdbscan scikit-learn==1.5.0

from hdbscan import HDBSCAN
```
<img width="1012" alt="Screenshot 2024-06-17 at 7 36 12 AM" src="https://github.com/scikit-learn-contrib/hdbscan/assets/80478925/9039e307-d4c7-46c3-ac5e-7196cd5c6525">

**Comment by lmcinnes** [comment]
The numpy 2.0 release might mean you have to ensure cython gets run to rebuild C sources. Potentially this can be solved the ``--no-binary`` option in pip install, but I'm not entirely sure if this is exactly the issue.

**Comment by lmcinnes** [comment]
It looks like numpy 2.0 is not going to play nice with cython and hdbscan here. Figuring out how to make it all work will take some time. In the meantime I've pinned the numpy version as <2 for a new hdbscan release so installing from PyPI (soon) will object to having hdbscan 0.8.37 and numpy 2.0. For other workarounds I would suggest looking to [fast_hdbcan](https://github.com/TutteInstitute/fast_hdbscan) which should work with numpy 2.0 right now.

**Comment by seberg** [comment]
@lmcinnes there should be nothing required except uploading no wheels.  I have opened https://github.com/scikit-learn-contrib/hdbscan/pull/644

**Comment by seberg** [comment]
Sorry, turns out there were some minor code tweaks needed.  And there is another issue, but I am not sure what it is, since it doesn't seem to be related to NumPy itself.

**Comment by jakirkham** [comment]
Thanks Sebastian and Leland! 🙏

Is there more still needed here?

Or do we just need a release and packages?
