### ISSUE TITLE
Is hdbscan using Parallel from joblib

### ISSUE THREAD

**Issue by sachinruk** [scikit-learn-contrib/hdbscan#74]
when I try to run the following code I'm getting the warning `UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1`.

Just wondering if the `RobustSingleLinkage` class specifically is using the `Parallel` class from `joblib`. Because that's the only way I can think of how parallel loops are being nested if anything.

If it is parallelising, is there a way to set the number of cores the same way it does in a normal HDBSCAN class?
```
def clusterParallel(i):
    global labels
    
    np.random.seed(i)
    idx = np.random.choice(len(data2), 25000, replace=False)
    clusterer = hdbscan.RobustSingleLinkage(k=30, cut=0.1)
    labels[idx,i] = clusterer.fit_predict(data2[idx])[:,None]

Parallel(n_jobs=4)(delayed(clusterParallel)(i) for i in range(8))
```

**Comment by lmcinnes** [comment]
Yes, we use parallel from joblib for parallelising computation of
core-distances. There is an n_jobs parameter (which may or may not be in
RobustSingleLinkage -- it if isn't I'll add it) that might alleviate the
problem if you set it to 1.

**Comment by sachinruk** [comment]
I'm afraid the `n_jobs` parameter is in `HDBSCAN` only and not in `RobustSingleLinkage`. 

Also while I'm here could you add an option to use all possible cores if `n_jobs = -1`. This will keep to scikits conventions.

Appreciate the help!

**Comment by lmcinnes** [comment]
Alright, I was worried that might be the case. I'll try and get that fixed
as soon as I get some time.

With regard to njobs = -1: that should already be the case in master --
although perhaps not in the current  release on PyPI
