### ISSUE TITLE
ValueError: Sparse distance matrix has multiple connected components!

### ISSUE THREAD

**Issue by eugmandel** [scikit-learn-contrib/hdbscan#82]
I was trying to run HDBSCAN with metric='precomputed' and getting this error: 

```
..../python2.7/site-packages/hdbscan/hdbscan_.pyc in _hdbscan_sparse_distance_matrix(X, min_samples, alpha, metric, p, leaf_size, gen_min_span_tree, **kwargs)
    172     if csgraph.connected_components(mutual_reachability_, directed=False,
    173                                     return_labels=False) > 1:
--> 174         raise ValueError('Sparse distance matrix has multiple connected'
    175                          ' components!\nRun hdbscan on each component.')
    176 

ValueError: Sparse distance matrix has multiple connected components!
Run hdbscan on each component.
```

The pairwise distance matrix that I pass as an argument to fit method is a sparse SciPy matrix in CSR format. Could you please explain the error? Thank you!

**Comment by lmcinnes** [comment]
Yes -- the issue is that if you view your CSR matrix as an adjacency matrix
for a graph then that graph has multiple connected components. That is to
say there are groups of points that are completely disjoint -- there are no
distance relations connecting them in any way. HDBSCAN can't handle that
right now. If you preprocess your data into those disjoint sets of points
and then run HDBSCAN on each of those groups independently then everything
should work fine.

For my own sake, what sort of error message would you have preferred to
see? Perhaps, until I actually get a more complete resolution to the
problem in place, I can have a better error message that explains the issue
more accurately? Also if you have a suggestion for where in the
documentation I could refer to this case?

Thanks.

**Comment by eugmandel** [comment]
Thank you for the answer! Actually, the matrix is sparse exactly because I threw away values greater than a certain threshold in order to keep the matrix manageable on one machine. The explanation makes sense. The phrasing from your answer ("there are groups of points that are completely disjoint -- there are no distance relations connecting them in any way") makes it much clearer to me - may be it's worth adding it to the error message.

If my data set was small, it looks like the easiest solution would be to recompute the pairwise distance matrix without leaving "empty cells" (essentially, dense). Unfortunately, the size of my dataset would make this dense matrix too big for my machine's memory. I will look into preprocessing the data set into subsets.

Thank you!

**Comment by lmcinnes** [comment]
If you can use a distance metric (or transform your data to allow you to
use a distance metric) supported by sklearn's ball-trees then you can
perform the computation in O(n log n) time and use only O(n log n) memory
to do it by passing the raw data directly. Of course if you have a more
complex or custom distance metric then your method will be the best
available.

**Comment by lmcinnes** [comment]
Thanks for the error message suggestion. I'll try to get it updated soon.

**Comment by erwin0825** [comment]
Any idea how I can use my sparse matrix to divide the dataset into multiple subsets?

**Comment by lmcinnes** [comment]
You should be able to use

    scipy.sparse.csgraph.connected_components

to get you the separate components of the sparse matrix. See [the documentation](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.sparse.csgraph.connected_components.html) for more details, but essentially it should provide you the number of components, and a label array that labels which points are in which component. Eventually I'll get around to handling all of this in the code myself, but it currently doesn't fit tidily with the existing API so I would have to do some internal refactoring to make it easy to gather all the results and present them in the right way (labels are easy, condensed trees etc. are harder).

**Comment by RichieHakim** [comment]
I did the following and it worked well:
```
def attach_fully_connected_node(d, dist_fullyConnectedNode=None):
    """
    This function takes in a sparse graph (csr_matrix) that has more than
     one component (multiple unconnected subgraphs) and appends another 
     node to the graph that is weakly connected to all other nodes.
    RH 2022
     
    Args:
        d (scipy.sparse.csr_matrix):
            Sparse graph with multiple components.
            See scipy.sparse.csgraph.connected_components
        dist_fullyConnectedNode (float):
            Value to use for the connection strengh to all other nodes.
            Value will be appended as elements in a new row and column at
             the ends of the 'd' matrix.
             
     Returns:
         d2 (scipy.sparse.csr_matrix):
             Sparse graph with only one component.
    """
    if dist_fullyConnectedNode is None:
        dist_fullyConnectedNode = (d.max() - d.min()) * 1000
    
    d2 = d.copy()
    d2 = scipy.sparse.vstack((d2, np.ones((1,d2.shape[1]))*dist_fullyConnectedNode))
    d2 = scipy.sparse.hstack((d2, np.ones((d2.shape[0],1))*dist_fullyConnectedNode))

    return d2.tocsr()


max_dist=(D.max() - D.min()) * 1000
hdbs = hdbscan.HDBSCAN(
    min_cluster_size=2,
    max_cluster_size=15,
    metric='precomputed',
    alpha=0.999,
    algorithm='generic',
    max_dist=max_dist
)
hdbs.fit(attach_fully_connected_node(
    D.tocsr(), 
    dist_fullyConnectedNode=max_dist
))
labels = hdbs.labels_[:-1]
```
Where `D` is my 'precomputed' distance matrix. Also note the use of the `max_dist` kwarg in the `hdbscan.HDBSCAN` initialization; this parameter is also appropriate for use as the `dist_fullyConnectedNode` in my function.

I would love a natively supported solution to this or some more details on how to best use the above suggestion of splitting the graph into connected components and running hdbscan on each.
That said, if this solution is valid, maybe we could add it in?
