### ISSUE TITLE
Robust Single Linkage hierarchy

### ISSUE THREAD

**Issue by peekxc** [scikit-learn-contrib/hdbscan#85]
This is less an issue and more a question for @lmcinnes, since github doesn't have messaging. 

It was noted in the main page that the "Robust Single Linkage Hierarchy" is also available for performing cutting. It seems to me that this is equivalent to the "HDBSCAN* hierarchy." But I randomly skimmed the 2015 HDBSCAN paper and noticed there was not reference in the paper to the 2010 paper "Rates of convergence of the cluster tree" by Chaudhuri and DasGupta. 

It seems intuitive to make this jump that they are equivalent, but seeing as it wasn't "proven" or anything in the paper, who figured that out?

**Comment by lmcinnes** [comment]
For the purposes of this work I made the link after I was directed to
Robust Single Linkage as an alternative algorithm and, in attempting the
implementation realised there was a clear equivalence. As you say, this
equivalence is fairly straightforward to see once you look at both
algorithms in the right light, so I imagine many other people who have
familiarity with the algorithms have also made this link. I don't know of
any published literature specifically demonstrating the equivalence however.

**Comment by peekxc** [comment]
Ahh, I see. Well, whoever made the connection, well done.
