### ISSUE TITLE
Prediction.approximate_predict returns nan probability values

### ISSUE THREAD

**Issue by matt24smith** [scikit-learn-contrib/hdbscan#96]
When I run hdbscan prediction.approximate_predict() on new points to predict, some values are returned as nan. Since these values still evaluate as float, it can be difficult to find the source of the error when using the approximate_predict function in code. Perhaps these values should be returned as 0?

Some info about my data used:
hdbscan clusterer object is created with bounded coordinate data. Object is generated with the following code: 

    clusterer = hdbscan.HDBSCAN(algorithm = 'prims_kdtree',
                                min_cluster_size=8, 
                                min_samples=10,
                                prediction_data=True, 
                                cluster_selection_method='leaf',
                                alpha=1,
                                gen_min_span_tree=False).fit(data)

`data` is of type zip(longitudeData, latitudeData)
`points_to_predict` is of type zip(newLongitudeData, newLatitudeData)

longitudeData, latitudeData, newLongitudeData, newLatitudeData are all verified as not containing nan values (all floats)

hdbscan version 0.8.8

**Comment by lmcinnes** [comment]
That seems a little odd. The predict code is still pretty new so may have
some edge cases that are still a problem. I'll try and look into it.

**Comment by lmcinnes** [comment]
I believe I have fixed the problem in the master branch -- if you could check out and build from master and let me know if that resolved it for you I would appreciate it.

**Comment by matt24smith** [comment]
This fixed the problem. Thanks!

**Comment by lmcinnes** [comment]
Excellent, glad to hear it.
