### ISSUE TITLE
MemoryError when inputting list of 100,000 strings

### ISSUE THREAD

**Issue by rf987** [scikit-learn-contrib/hdbscan#98]
I'm getting a memory error when trying to cluster a large list of strings.  Here's my code:

`    
    from sklearn.feature_extraction.text import TfidfVectorizer
    import numpy as np
    import hdbscan    

    vect = TfidfVectorizer(stop_words="english",analyzer ="word",max_features=5000)
    X = vect.fit_transform(text_list)
    clusterer = hdbscan.HDBSCAN(min_cluster_size=smallest_cluster_size)
    clusterer.fit(X)
`

here is the full error I receive when calling clusterer.fit:
    clusterer.fit(X)
  File "C:\Python27\lib\site-packages\hdbscan\hdbscan_.py", line 854, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "C:\Python27\lib\site-packages\hdbscan\hdbscan_.py", line 576, in hdbscan
    gen_min_span_tree, **kwargs)
  File "C:\Python27\lib\site-packages\sklearn\externals\joblib\memory.py", line 283, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\hdbscan\hdbscan_.py", line 123, in _hdbscan_generic
    distance_matrix = pairwise_distances(X, metric=metric, **kwargs)
  File "C:\Python27\lib\site-packages\sklearn\metrics\pairwise.py", line 1240, in pairwise_distances
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "C:\Python27\lib\site-packages\sklearn\metrics\pairwise.py", line 1083, in _parallel_pairwise
    return func(X, Y, **kwds)
  File "C:\Python27\lib\site-packages\sklearn\metrics\pairwise.py", line 245, in euclidean_distances
    distances = safe_sparse_dot(X, Y.T, dense_output=True)
  File "C:\Python27\lib\site-packages\sklearn\utils\extmath.py", line 184, in safe_sparse_dot
    ret = a * b
  File "C:\Python27\lib\site-packages\scipy\sparse\base.py", line 369, in __mul__
    return self._mul_sparse_matrix(other)
  File "C:\Python27\lib\site-packages\scipy\sparse\compressed.py", line 540, in _mul_sparse_matrix
    indices = np.empty(nnz, dtype=idx_dtype)
MemoryError

Is there a limit to how much data hdbscan can process?  Should I keep the lists small?  Or is there a way to fix this error so it can handle large datasets?

I'm running Windows, 64bit, with 18Gb of ram

Thank you

**Comment by lmcinnes** [comment]
There are a few different paths through the code, and some can handle large datasets while others cannot. The one that your data ended up taking computes a pairwise distance matrix which is the cause of the memory error.  I admit to not being certain as to why your data is tripping conditions to end up using the generic algorithm. You can force a specific algorithm to be used:

    clusterer = hdbscan.HDBSCAN(min_cluster_size=smallest_cluster_size, algorithm='boruvka_kdtree')
    clusterer.fit(X)

should force it to use an algorithm that can cope with data on the scale that you have, but that may break (as presumably there is a reason the code is using the generic algorithm). Potentially it is because X is a sparse matrix -- if that's the case you may want to either dimension reduce the matrix, or make a dense matrix of it as that may result in hdbscan using the correct low memory algorithm.

**Comment by fredtony** [comment]
@lmcinnes I had the same problem on a very sparse symmetric csr matrix. When I run `fit_predict` with `algorithm='boruvka_kdtree'`, I get:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-1835cd950289> in <module>()
      1 clusterer = hdbscan.HDBSCAN(min_cluster_size=5, algorithm='boruvka_kdtree')
----> 2 cluster_labels = clusterer.fit_predict(tr_csr)

..\Anaconda2\envs\tensorflow\lib\site-packages\hdbscan\hdbscan_.py in fit_predict(self, X, y)
    884             cluster labels
    885         """
--> 886         self.fit(X)
    887         return self.labels_
    888 

..\Anaconda2\envs\tensorflow\lib\site-packages\hdbscan\hdbscan_.py in fit(self, X, y)
    862          self._condensed_tree,
    863          self._single_linkage_tree,
--> 864          self._min_spanning_tree) = hdbscan(X, **kwargs)
    865 
    866         if self.prediction_data:

..\Anaconda2\envs\tensorflow\lib\site-packages\hdbscan\hdbscan_.py in hdbscan(X, min_cluster_size, min_samples, alpha, metric, p, leaf_size, algorithm, memory, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, cluster_selection_method, allow_single_cluster, match_reference_implementation, **kwargs)
    554                                          approx_min_span_tree,
    555                                          gen_min_span_tree,
--> 556                                          core_dist_n_jobs, **kwargs)
    557         elif algorithm == 'boruvka_balltree':
    558             if metric not in BallTree.valid_metrics:

..\Anaconda2\envs\tensorflow\lib\site-packages\sklearn\externals\joblib\memory.py in __call__(self, *args, **kwargs)
    281 
    282     def __call__(self, *args, **kwargs):
--> 283         return self.func(*args, **kwargs)
    284 
    285     def call_and_shelve(self, *args, **kwargs):

..\Anaconda2\envs\tensorflow\lib\site-packages\hdbscan\hdbscan_.py in _hdbscan_boruvka_kdtree(X, min_samples, alpha, metric, p, leaf_size, approx_min_span_tree, gen_min_span_tree, core_dist_n_jobs, **kwargs)
    281         X = X.astype(np.float64)
    282 
--> 283     tree = KDTree(X, metric=metric, leaf_size=leaf_size, **kwargs)
    284     alg = KDTreeBoruvkaAlgorithm(tree, min_samples, metric=metric,
    285                                  leaf_size=leaf_size // 3,

sklearn\neighbors\binary_tree.pxi in sklearn.neighbors.kd_tree.BinaryTree.__init__ (sklearn\neighbors\kd_tree.c:9130)()

..\Anaconda2\envs\tensorflow\lib\site-packages\numpy\core\numeric.py in asarray(a, dtype, order)
    529 
    530     """
--> 531     return array(a, dtype, copy=False, order=order)
    532 
    533 

ValueError: setting an array element with a sequence.

Any thoughts on how I could resolve this? Is it a bug or can I set different options when running the code? I'm using python 3.5 and would be happy to provide more specs if that would help solve the problem.

Thanks!

**Comment by lmcinnes** [comment]
That looks like a different issue, but is definitely an issue -- it comes down to he KDTree from sklearn not actually working on your dataset. If you can verify that it is just the tree that would certainly help:

    from sklearn.neighbors import KDTree
    tree = KDTree(tr_csr)

I think the short answer here is that KDTree's don't accept sparse input. Unfortunately the fast/low memory algorithm version of hdbscan requires KDTrees (or a similar tree structure). I'm afriad there may not be any easy answers here.

**Comment by fredtony** [comment]
Thanks for taking a look! Too bad it doesn't seem like it will work with data set, but thanks for the library anyway. Seems useful when its not an odd case like mine :)

**Comment by balazsrobi** [comment]
I also had the same problem, I experimented with different _min_cluster_size_ and _min_samples_ parameters.
