### ISSUE TITLE
Update pypi with newer tags

### ISSUE THREAD

**Issue by loisaidasam** [scikit-learn-contrib/hdbscan#99]
I noticed that the latest version of hdbscan on [pypi](https://pypi.python.org/pypi/hdbscan) is `0.8.8`.

Any reason why it doesn't have the updates to `0.8.10`?

**Comment by lmcinnes** [comment]
Because I'm a little slow -- the patches were very minor so I was not
especially motivated to roll out a fix. Sorry about that! I'll get on it.

**Comment by lmcinnes** [comment]
Okay, should be on PyPI now, and conda-forge imminently. Sorry for the delay.

**Comment by loisaidasam** [comment]
Thanks @lmcinnes! 👍
